export const tableHeader = [
    'Số thứ tự',
    'Nhân viên',
    'Trạng thái',
    'Mã phiếu',
    'Mã KH',
    'Tên khách hàng',
    'Địa chỉ',
    'Ngày trả',
    'Phải trả',
    'Nguồn',
    'Ngày tạo',
    'Người tạo',
    'Ngày sửa',
    'Người sửa',
    'Diễn giải',
];
