export const headerOrderReportTable: string[] = [
    'STT',
    'Mã nhân viên',
    'Tên nhân viên',
    'Phòng nhóm',
   // 'Nguồn',
    'Mã đơn đặt',
    'Ngày đơn đặt hàng',
    'Mã khách hàng',
    'Tên khách hàng',
    // 'Số lần bán',
   // 'Số lần trả',
    'Địa chỉ',
    'Khu vực',
    'Kênh',
    'Nhóm khách',
    //'Loại khách',
    'Mã sản phẩm',
    'Tên sản phẩm',
   // 'Mã kho',
    //'Tên kho',
   // 'Ghi chú sp',
    //'Ngành hàng',
    //'Nhãn hiệu',
    'Số lượng đặt',
    //'Tên CTKM',
    'Số lượng KM',
    'ĐVT',
    'Đơn giá',
    'Thành tiền (SL đặt x giá)',
    //'Tiền VAT (từng SP)',
    'Chiết khấu(%) (từng SP)',
    'Tiền chiết khấu (từng SP)',
    'Thành tiền (tổng bill)',
    // 'Chiết khấu(%) (tổng bill)',
    'Tiền chiết khấu (tổng bill)',
    'Thanh toán',
    'Diễn giải',
];

export const headerSaleReceiptTable: string[] = [
    'STT',
    'Ngày chứng từ',
    'Số chứng từ',
    'Mã khách hàng',
    'Tên khách hàng',
    'Địa chỉ',
    'Quận huyện',
    'Tỉnh thành',
    'Mã phòng nhóm',
    'Tên nhân viên đặt hàng',
    'Mã hàng',
    'Tên hàng',
    'ĐVT',
    'Số lượng bán',
    'Đơn giá',
    'Doanh số bán',
    'Chiết khấu',
    'Số lượng trả lại',
    'Giá trị trả lại',
    'Doanh số thuần',
    'Diễn giải chung',
];
