export const tableHeader = [
    '#',
    'Ngày',
    'Mã nhân viên',
    'Tên nhân viên',
    'Phòng nhóm	',
    'Nguồn',
    'Mã đơn đặt',
    'Ngày đơn đặt hàng',
    'Mã khách',
    'Tên khách',
    'Địa chỉ',
    'Khu vực',
    'Kênh',
    'Nhóm khách',
    'Loại khách',
    'Mã sản phẩm',
    'Tên sản phẩm',
    'Ghi chú sp',
    'Ngành hàng',
    'Nhãn hiệu',
    'Số lượng đặt',
    'Tên CTKM',
    'Số lượng KM',
    'ĐVT',
    'Đơn giá',
    'Thành tiền (SL đặt x giá)',
    'Chiết khấu(%) (từng SP)',
    'Tiền chiết khấu (từng SP)',
    'Chiết khấu(%) (tổng bill)',
    'Tiền chiết khấu (tổng bill)',
    'Thanh toán',
    'Doanh thu (-VAT)',
    'Diễn giải'
];
