export const PurchaseHeader = [
    'Người đặt',
    'Trạng thái',
    'Mã phiếu',
    'Mã KH',
    'Tên KH',
    'Địa chỉ',
    'Ngày đặt',
    'Tổng tiền',
    'Người duyệt',
    'Ngày duyệt',
    'Nguồn',
    'Ngày tạo',
    'Người tạo',
    'Ngày sửa',
    'Người sửa',
    'Diễn giải',
];

export const SaleHeader = [
    'Người đặt',
    'Người bán',
    'Trạng thái',
    'Mã phiếu',
    'Mã KH',
    'Tên khách hàng',
    'Địa chỉ',
    'Ngày đặt',
    'Ngày bán',
    'Tổng tiền',
    'Ngày tạo',
    'Người tạo',
    'Ngày sửa',
    'Người sửa',
    'Diễn giải',
];
